# CloudNativePG Backup - konfiguracja backupów
# 
# CloudNativePG ma wbudowany system backupów używający Barman
# 
# Wymagania:
# - CloudNativePG Cluster musi być utworzony
# - S3-compatible storage (opcjonalne, można użyć lokalnego PVC)
#
# Przykład z S3:
# 1. Utwórz secret z credentials S3:
#    kubectl create secret generic backup-credentials \
#      --from-literal=ACCESS_KEY_ID=your_key \
#      --from-literal=SECRET_ACCESS_KEY=your_secret \
#      -n plusworkflow
#
# 2. Zastosuj ten manifest
#
# Alternatywnie, możesz użyć lokalnego PVC (bez S3)

apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-cluster-backup
  namespace: plusworkflow
spec:
  cluster:
    name: postgres-cluster
  method: barmanObjectStore
  # S3 backup (odkomentuj jeśli masz S3)
  # barmanObjectStore:
  #   destinationPath: "s3://backup-bucket/postgres-cluster"
  #   s3Credentials:
  #     accessKeyId:
  #       name: backup-credentials
  #       key: ACCESS_KEY_ID
  #     secretAccessKey:
  #       name: backup-credentials
  #       key: SECRET_ACCESS_KEY
  #   wal:
  #     retention: "7d"
  #   data:
  #     retention: "30d"
  #   tags:
  #     - backup
  #     - daily

---
# ScheduledBackup - automatyczne backupy
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-cluster-scheduled-backup
  namespace: plusworkflow
spec:
  cluster:
    name: postgres-cluster
  schedule: "0 2 * * *"  # Codziennie o 2:00
  method: barmanObjectStore
  # S3 backup (odkomentuj jeśli masz S3)
  # barmanObjectStore:
  #   destinationPath: "s3://backup-bucket/postgres-cluster"
  #   s3Credentials:
  #     accessKeyId:
  #       name: backup-credentials
  #       key: ACCESS_KEY_ID
  #     secretAccessKey:
  #       name: backup-credentials
  #       key: SECRET_ACCESS_KEY
  #   wal:
  #     retention: "7d"
  #   data:
  #     retention: "30d"
  #   immediateCheckpoint: false

