# CloudNativePG Cluster - PostgreSQL z automatyczną replikacją
# 
# Wymagania:
# 1. CloudNativePG Operator musi być zainstalowany:
#    ./install-cloudnativepg.sh
#    lub
#    kubectl apply -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.22/releases/cnpg-1.22.0.yaml
#
# 2. Secret postgres-secret musi istnieć (używa tego samego co StatefulSet)
#
# Funkcjonalności:
# - Automatyczna replikacja (streaming replication)
# - Automatyczny failover
# - Backup i restore (wbudowane)
# - Monitoring i health checks
#
# Instalacja:
# kubectl apply -f manifest-10-postgres-cloudnativepg.yaml

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: plusworkflow
spec:
  # Liczba instancji (1 primary + 2 replicas)
  instances: 3
  
  # Konfiguracja PostgreSQL
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"
  
  # Image PostgreSQL
  # CloudNativePG 1.22.0 wspiera postgres:15 (oficjalnie testowane)
  # postgres:16 wymaga nowszej wersji operatora (1.23+)
  # postgres:15-alpine ma uid 26 co powoduje "user does not exist"
  imageName: postgres:15
  
  # Bootstrap - używa secret typu kubernetes.io/basic-auth
  # Secret musi mieć klucze: username i password
  bootstrap:
    initdb:
      database: plusworkflow
      owner: postgres
      secret:
        name: postgres-secret-cnpg  # CloudNativePG wymaga secret typu kubernetes.io/basic-auth
  
  # Storage
  storage:
    size: 20Gi
    storageClass: local-path  # Zmień na longhorn jeśli chcesz użyć Longhorn
  
  # Zasoby
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

  # PostgresUID/GID - WORKAROUND dla CloudNativePG 1.22.0
  # Operator 1.22.0 ma bug z detectowaniem user ID z obrazu postgres:15
  # Defaultowo ustawia 26 (Alpine) zamiast 999 (Debian)
  postgresUID: 999
  postgresGID: 999
  
  # Backup (opcjonalne - można skonfigurować później)
  # backup:
  #   barmanObjectStore:
  #     destinationPath: "s3://backup-bucket/postgres"
  #     s3Credentials:
  #       accessKeyId:
  #         name: backup-credentials
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: backup-credentials
  #         key: SECRET_ACCESS_KEY
  #     wal:
  #       retention: "7d"
  #     data:
  #       retention: "30d"
  
  # Monitoring (opcjonalne)
  # monitoring:
  #   enabled: true
  #   podMonitorEnabled: true

# UWAGA: CloudNativePG automatycznie tworzy następujące serwisy:
# - postgres-cluster-rw   (read-write, wskazuje na primary)
# - postgres-cluster-ro   (read-only, wskazuje na replicas)
# - postgres-cluster-r    (read, dla replikacji)
#
# Aby połączyć się z bazą, użyj:
#   postgres-cluster-rw.plusworkflow.svc.cluster.local:5432
#
# Jeśli potrzebujesz LoadBalancer lub NodePort, utwórz osobny Service
# wskazujący na postgres-cluster-rw, np:
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-lb
# spec:
#   type: LoadBalancer
#   selector:
#     cnpg.io/cluster: postgres-cluster
#     cnpg.io/instanceRole: primary
#   ports:
#     - port: 5432
#       targetPort: 5432

