---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: plusworkflow
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: plusworkflow
spec:
  type: LoadBalancer
  selector:
    app: postgres
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
